import type { ReactElement } from 'react'
import Head from 'next/head'
import { Grid, Box } from '@material-ui/core'

// src
import Layout from '../src/templates/Layout'

interface IndexProps {
  side: string
}

export default function Index({ side }: IndexProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {side ?? 'client'} side

      <Grid>
        Vrode rabotaet
      </Grid>

      <Box p={4}>
        A vrode net
      </Box>
    </>
  )
}

Index.getLayout = function getLayout(page: ReactElement) {
  return (
      <Layout>{page}</Layout>
  )
}

export async function getServerSideProps(context: any) {
  return {
    props: {
      side: 'server'
    },
  }
}
