import type { ReactElement } from 'react'
import Head from 'next/head'

// src
import Layout from '../src/templates/Layout'

export default function Index({ side }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {side ?? 'client'} side
    </>
  )
}

Index.getLayout = function getLayout(page: ReactElement) {
  return (
      <Layout>{page}</Layout>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      side: 'server'
    },
  }
}
